#!/bin/sh
#usage: [path/to/autolinks] delimiter(chroot root dir) [absolute/path/to/savelinks]
#it is recommended to provide savelinks location in the format of $(pwd)/[relative/path/to/savelinks]
dest="$(pwd)"
delim="$1"
path="$2"
find "$dest" -type l | grep -o '^.*/' | sort -u > dlinks
cat dlinks | while read line
do
cd "$line"
$path/savelinks $(basename $line)/
done
