#!/bin/sh
#usage: path/to/savelinks [chroot directory]/relative/path/to/pwd/
#NOTE: '/' after the target directory name is strictly required, not to irreversibly break all the l2symlink directions.
#depth is used to get rid of remaining upper dir names, such as 'bin' or 'usr'. set it to 2 when pwd is right under /. Adjust the value between 2 and 4 if the script is not working properly.
dest="$(pwd)"
delim="$1"
find $dest -type l | sed 's,^,ls -l ,' | sed 's,$, | cut -d: -f2- | cut -d" " -f2- | grep .l2s.,' > linker
sh linker > links
cat links | while read line
do
    link="$(echo $line | cut -d' ' -f1 | sed 's,^.*'$delim',,')"
    src="$(echo $line | cut -d' ' -f3 | sed 's,^.*'$delim',,')"
    ln -sf "$src" "$link"
done
