#!/bin/sh
echo export https_proxy=socks5h://localhost:$1 >> .$(cat /etc/passwd | grep ^user: | grep -o /.\*sh$ | sed s,^.\*bin/,,)rc
echo export http_proxy=socks5h://localhost:$1 >> .$(cat /etc/passwd | grep ^user: | grep -o /.\*sh$ | sed s,^.\*bin/,,)rc
